Repository Ddareunging/Ddareunging-Server, pull requests merged in 2024-05, with the labels that each got.

#14 [Feat] 날씨 정보 조회 API 구현
  .gitignore
  build.gradle
  src/main/java/ddareunging/ddareunging_server/config/SwaggerConfig.java
  src/main/java/ddareunging/ddareunging_server/controller/HomeController.java
  src/main/java/ddareunging/ddareunging_server/controller/HomeWeatherController.java
  src/main/java/ddareunging/ddareunging_server/controller/RegionController.java
  src/main/java/ddareunging/ddareunging_server/domain/Region.java
  src/main/java/ddareunging/ddareunging_server/domain/Weather.java
  src/main/java/ddareunging/ddareunging_server/dto/WeatherResponseDTO.java
  src/main/resources/application.properties
  src/main/resources/regionList.csv
Labels: :sparkles: feature

#15 [Fix] 날씨 조회 API 구 기반 조회로 변경 & 에러 해결
  src/main/java/ddareunging/ddareunging_server/controller/HomeController.java
  src/main/java/ddareunging/ddareunging_server/controller/HomeWeatherController.java
  src/main/java/ddareunging/ddareunging_server/controller/RegionController.java
  src/main/java/ddareunging/ddareunging_server/domain/Region.java
  src/main/resources/regionListByDistrict.csv
Labels: :recycle: refactor, :hammer: fix

#19 [CI] 배포 서버 오류 해결
  .gitignore
  src/main/java/ddareunging/ddareunging_server/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: :rotating_light: hotfix, :construction_worker: ci

#21 [Fix] 날씨 조회 API 새벽 시간대 조회 코드 수정
  src/main/java/ddareunging/ddareunging_server/controller/HomeController.java
  src/main/java/ddareunging/ddareunging_server/service/HomeWeatherService.java
Labels: :hammer: fix

#27 [Feat] 지도 내 대여소 조회 API 구현
  src/main/java/ddareunging/ddareunging_server/controller/HomeController.java
  src/main/java/ddareunging/ddareunging_server/controller/MapController.java
  src/main/java/ddareunging/ddareunging_server/controller/RentalController.java
  src/main/java/ddareunging/ddareunging_server/domain/Rental.java
  src/main/java/ddareunging/ddareunging_server/dto/MapResponseDTO.java
  src/main/java/ddareunging/ddareunging_server/repository/RentalRepository.java
  src/main/java/ddareunging/ddareunging_server/service/MapService.java
  src/main/resources/application.yml
  src/main/resources/rental.csv
  src/main/resources/rental.csv~
Labels: :sparkles: feature

#30 [Refactor] CorssOrigin 설정 추가
  src/main/java/ddareunging/ddareunging_server/controller/HomeController.java
  src/main/java/ddareunging/ddareunging_server/controller/MapController.java
  src/main/java/ddareunging/ddareunging_server/controller/RegionController.java
  src/main/java/ddareunging/ddareunging_server/controller/RentalController.java
  src/main/java/ddareunging/ddareunging_server/controller/TestController.java
Labels: :recycle: refactor

#31 [Feat] 로그인 및 회원 정보 관리 구현
  .DS_Store
  build.gradle
  src/main/java/ddareunging/ddareunging_server/DdareungingServerApplication.java
  src/main/java/ddareunging/ddareunging_server/Dto/LoginDto.java
  src/main/java/ddareunging/ddareunging_server/config/MvcConfig.java
  src/main/java/ddareunging/ddareunging_server/domain/User.java
  src/main/java/ddareunging/ddareunging_server/repository/UserRepository.java
  src/main/java/ddareunging/ddareunging_server/service/KakaoService.java
  src/main/java/ddareunging/ddareunging_server/service/UserService.java
  src/main/java/ddareunging/ddareunging_server/util/FileUploadUtil.java
  src/main/java/ddareunging/ddareunging_server/web/controller/LoginController.java
  src/main/java/ddareunging/ddareunging_server/web/controller/LoginPageController.java
  src/main/java/ddareunging/ddareunging_server/web/controller/MyPageController.java
  src/main/java/ddareunging/ddareunging_server/web/controller/UserProfileController.java
  src/main/resources/application.yml
  src/main/resources/static/images/kakao_login_medium_narrow.png
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/updateInfo.html
  src/main/resources/templates/updateMyPage.html
  src/main/resources/templates/updateProfile.html
  src/main/resources/templates/userInfo.html
  user-profile-photos/.DS_Store
  user-profile-photos/3460794882/1654266481549.png
  user-profile-photos/3460794882/6.jpg
  user-profile-photos/3460794882/Untitled (1).png
  user-profile-photos/3460794882/박수아_서명.png
Labels: :sparkles: feature

#33 [Fix] merge 중 발생한 에러 해결 및 url 경로 정리
  build.gradle
  src/main/java/ddareunging/ddareunging_server/controller/HomeController.java
  src/main/java/ddareunging/ddareunging_server/web/controller/LoginController.java
  src/main/java/ddareunging/ddareunging_server/web/controller/LoginPageController.java
  src/main/java/ddareunging/ddareunging_server/web/controller/MyPageController.java
  src/main/java/ddareunging/ddareunging_server/web/controller/UserProfileController.java
  src/main/resources/application.yml
  src/main/resources/templates/mypage-updateInfo.html
  src/main/resources/templates/mypage-updateMyPage.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/userinfo.html
Labels: :hammer: fix

#39 [Feat] 프론트 연동
  src/main/java/ddareunging/ddareunging_server/controller/ApiTestController.java
  src/main/java/ddareunging/ddareunging_server/web/controller/LoginPageController.java
  src/main/resources/application.yml
  src/main/resources/static/css/224.869aedb9.chunk.css
  src/main/resources/static/css/main.6c39f2a8.css
  src/main/resources/static/index.html
  src/main/resources/static/js/224.3093597a.chunk.js
  src/main/resources/static/js/453.51079d00.chunk.js
  src/main/resources/static/js/main.9ae17e1c.js
  src/main/resources/static/public/course_banner_1.png
  src/main/resources/static/public/course_banner_2.png
  src/main/resources/static/public/course_banner_3.png
  src/main/resources/static/public/detail_ex.png
  src/main/resources/static/public/home_banner_1.png
  src/main/resources/static/public/home_banner_2.png
  src/main/resources/static/public/home_banner_3.png
Labels: :sparkles: feature

#41 [Fix] CORS 관련 설정 수정
  src/main/java/ddareunging/ddareunging_server/config/WebConfig.java
  src/main/resources/static/index.html
Labels: :hammer: fix

#47 [Feat] 프론트 연동
  src/main/java/ddareunging/ddareunging_server/config/MvcConfig.java
  src/main/java/ddareunging/ddareunging_server/config/SinglePageAppController.java
  src/main/java/ddareunging/ddareunging_server/config/WebMvcConfig.java
  src/main/resources/static/css/main.3cc3b430.css
  src/main/resources/static/css/main.ad191dfb.css
  src/main/resources/static/index.html
  src/main/resources/static/js/224.8e132d5b.chunk.js
  src/main/resources/static/js/main.483908ec.js
  src/main/resources/static/js/main.60e3ea29.js
  src/main/resources/static/public/ch.jpg
  src/main/resources/static/public/gung.jpg
  src/main/resources/static/public/mang.jpg
  src/main/resources/static/public/si.jpg
  src/main/resources/static/public/song.jpg
  src/main/resources/static/public/south_han1.jpg
  src/main/resources/static/public/south_han2.jpg
  src/main/resources/static/public/yang.jpg
  src/main/resources/static/public/yeo.jpg
Labels: :sparkles: feature
